#!/bin/sh

disable_usb_hid=1

if [ ! -f /boot/browserscreen.txt ]; then
	mount /boot
fi

if [ -f /boot/browserscreen.txt ]; then
	. /boot/browserscreen.txt
fi

if [ $disable_usb_hid -eq 0 ]; then
	exit 1
fi

exit 0
